<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TLio.Json" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Client" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Extensions.Text" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Extensions.Math" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Extensions.TimeDate" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Extensions.Looping" Version="$(TLioVersion)" />
  </ItemGroup>

</Project>
