<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nuplane" Version="0.0.10" />
    <PackageReference Include="Nuplane.Abstractions" Version="0.0.10" />
    <PackageReference Include="Nuplane.Sources.Directory" Version="0.0.10" />
    <PackageReference Include="Nuplane.Loading" Version="0.0.10" />
    <PackageReference Include="Nuplane.Loading.Abstractions" Version="0.0.10" />
    <PackageReference Include="Nuplane.Loading.Api" Version="0.0.10" />
    <PackageReference Include="CShells" Version="0.0.28" />
    <PackageReference Include="CShells.Abstractions" Version="0.0.28" />
    <PackageReference Include="CShells.AspNetCore" Version="0.0.28" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TLio.Core" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Commands" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Functions" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Client" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Json" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Xml" Version="$(TLioVersion)" />
    <PackageReference Include="TLio.Yaml" Version="$(TLioVersion)" />
  </ItemGroup>

</Project>
